import "./globals.css";
import { Inter } from "next/font/google";
import { ClientApolloProvider } from "./provider/ClientAppoloProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PineQuest",
  description: "Generated by Team Debuggers",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ClientApolloProvider>{children}</ClientApolloProvider>
      </body>
    </html>
  );
}
